### ISSUE TITLE
Part 1 - MVP - Configure Framework To Allow Fully-Zeused Mission

### ISSUE THREAD

**Issue by dgibso29** [Bubbus/CA-Halloween-2021#12]

**Comment by Bubbus** [comment]
This needs us to define our player platoon structure so we can set up radio and marker structure, other than that I've polished off the config you started.

**Comment by dgibso29** [comment]
> This needs us to define our player platoon structure so we can set up radio and marker structure, other than that I've polished off the config you started.

Platoon structure as discussed in Discord
![image](https://user-images.githubusercontent.com/22088666/133833634-b3901873-8faa-48a3-8dc2-ecf6d2ba8a28.png)

**Comment by Bubbus** [comment]
Added platoon and remaining config files.
