### ISSUE TITLE
Review mission info pages

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/CA-Halloween-2021#2]
Take a look at the mission info pages, fill-in any blanks, address concerns, make changes etc.  This issue is complete once you've had a look at each of the pages below and feel like they're useful, agreeable and complete enough to use as reference while missionmaking.

https://github.com/Bubbus/CA-Halloween-2021/wiki/Part-1,-Tanoa
https://github.com/Bubbus/CA-Halloween-2021/wiki/Part-2,-Cam-Lao-Nam
https://github.com/Bubbus/CA-Halloween-2021/wiki/Part-3,-Cam-Lao-Nam

**Comment by dgibso29** [comment]
Reviewed concerns in [Part 2](https://github.com/Bubbus/CA-Halloween-2021/wiki/Part-2,-Cam-Lao-Nam) -- Take a look and adjust/ask/etc as you see fit @Bubbus.
